### ISSUE TITLE
Missing typing-extensions dependency

### ISSUE THREAD

**Issue by philipp-schmidt** [open-feature/python-sdk-contrib#97]
`python3 -c "from openfeature.contrib.provider.flagd import FlagdProvider"`

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/test/.venv/lib/python3.10/site-packages/openfeature/contrib/provider/flagd/__init__.py", line 1, in <module>
    from .provider import FlagdProvider
  File "/tmp/test/.venv/lib/python3.10/site-packages/openfeature/contrib/provider/flagd/provider.py", line 32, in <module>
    from .resolvers import AbstractResolver, GrpcResolver, InProcessResolver
  File "/tmp/test/.venv/lib/python3.10/site-packages/openfeature/contrib/provider/flagd/resolvers/__init__.py", line 3, in <module>
    from typing_extensions import Protocol
ModuleNotFoundError: No module named 'typing_extensions'
```

**Comment by federicobond** [comment]
Thanks for the report @philipp-schmidt. I have opened a pull request with a fix.

**Comment by philipp-schmidt** [comment]
Thanks!

Openfeature tutorial page installs this package, should probably be removed:
https://openfeature.dev/docs/tutorials/getting-started/python#step-3-add-the-openfeature-sdk
